#! /bin/python3

# import libs
import argparse
import subprocess 
import os

# Version
version="1.0.2"
dist="PikaOS 3"
image="/cdrom/casper/filesystem.squashfs"

# Print Program info
print("pikainstall " + version + ": PikaOS terminal installer! for " + dist + ".")

### text files
_REFIND_SETUP_FILE = """#!/usr/bin/bash
touch /boot/refind_linux.conf
echo '"'Boot with standard options'"'  '"'nvidia-drm.modeset=1 root=UUID={ROOT_PART_UUID} quiet splash ---'"'  > /boot/refind_linux.conf
echo '"'Boot with logging'"'  '"'nvidia-drm.modeset=1 root=UUID={ROOT_PART_UUID} ---'"'  >>  /boot/refind_linux.conf
echo '"'Boot with safe graphics'"'  '"'nvidia-drm.modeset=1 root=UUID={ROOT_PART_UUID} nomodeset ---'"'  >>  /boot/refind_linux.conf
"""

_CRYPTTAB_ROOT_SETUP_FILE = """#!/usr/bin/bash
cat /etc/crypttab
echo "crypt_root	UUID={ROOT_PART_UUID}	none	luks,discard" > /etc/crypttab
"""

_CRYPTTAB_SETUP_FILE = """#!/usr/bin/bash
cat /etc/crypttab
echo "crypt_home	UUID={HOME_PART_UUID}	/keyfile.txt    	luks" >> /etc/crypttab
touch /keyfile.txt
openssl genrsa > /keyfile.txt
echo "{LUKS_PASSWD}" | cryptsetup luksAddKey UUID={HOME_PART_UUID}	/keyfile.txt -
"""


# Global Functions
## List to string
def listToString(s):
    # initialize an empty string
    str1 = ""
    # traverse in the string
    for ele in s:
        str1 += ele
    # return string
    return str1

# Setup Command line arguments
parser = argparse.ArgumentParser()
parser.add_argument("-r", "--root", help="The Path where root is mounted to.", metavar="/mnt/root", default=argparse.SUPPRESS, required=True, nargs=1)
parser.add_argument("-b", "--boot", help="The Path where boot is mounted to.", metavar="/mnt/root/boot", default=argparse.SUPPRESS, required=True, nargs=1)
parser.add_argument("-e", "--efi", help="The Path where EFI is mounted to.", metavar="/mnt/root/boot/efi", default=argparse.SUPPRESS, required=True, nargs=1)
parser.add_argument("-H", "--home", help="The Path where home is mounted to.", metavar="/mnt/root/home", default=None, nargs=1)
args = parser.parse_args()

# Print all command-line arguments.
print("\nParsed arguments: {}".format(args))
# Get root info
## Root UUID
root_uuid_command= subprocess.Popen(['/usr/lib/pika/pikainstall/partition-helper.sh', 'uuid'] + args.root, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
root_uuid = root_uuid_command.stdout.readline().decode("utf-8").strip()
## Root Encryption Device
root_encrypt_command = subprocess.Popen(['/usr/lib/pika/pikainstall/partition-helper.sh', 'encrypt'] + args.root, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
root_encrypt = root_encrypt_command.stdout.readline().decode("utf-8").strip()
## Print Root info
print("\nRoot UUID: {}".format(root_uuid))  
if root_encrypt == "luks_none":
    print("Root Encryption Device: Root is not encrypted!") 
else:
    print("Root Encryption Device: {}".format(root_encrypt))  
# Get Boot info
## Boot UUID
boot_uuid_command= subprocess.Popen(['/usr/lib/pika/pikainstall/partition-helper.sh', 'uuid'] + args.boot, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
## Print Boot
boot_uuid = boot_uuid_command.stdout.readline().decode("utf-8").strip()
print("\nBoot UUID: {}".format(boot_uuid))
# Get EFI info
## EFI UUID
efi_uuid_command= subprocess.Popen(['/usr/lib/pika/pikainstall/partition-helper.sh', 'uuid'] + args.efi, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
efi_uuid = efi_uuid_command.stdout.readline().decode("utf-8").strip()
## Print EFI Info
print("\nEFI UUID: {}".format(efi_uuid))
# Get Home info is exists
if args.home is not None:
    ## Home UUID
    home_uuid_command = subprocess.Popen(['/usr/lib/pika/pikainstall/partition-helper.sh', 'uuid'] + args.home, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    home_uuid = home_uuid_command.stdout.readline().decode("utf-8").strip()
    ## Encryption
    home_encrypt_command = subprocess.Popen(['/usr/lib/pika/pikainstall/partition-helper.sh', 'encrypt'] + args.home, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    home_encrypt = home_encrypt_command.stdout.readline().decode("utf-8").strip()
    print("\nHome UUID: {}".format(home_uuid))  
    if home_encrypt == "luks_none":
        print("Home Encryption Device: Home is not encrypted!") 
    else:
        print("Home Encryption Device: {}".format(home_encrypt))
        ## Ask user for Home luks partition password for the key-filing process
        print("\nPlease enter the LUKS password for the device" + home_encrypt + " :")
        home_passwd = input("Warning: Do not enter this incorrectly or late installation will fail! ")
    
    
# Make sure to avoid any mounts pointing at the partition
if root_uuid == boot_uuid:
    print("Error: Root and Boot are mounted on the same drive, please place boot on it's own partition.")
    exit(1)
elif root_uuid == efi_uuid:
    print("Error: Root and EFI are mounted on the same drive, please place EFI on it's own partition.")
    exit(1)
elif boot_uuid == efi_uuid:
    print("Error: Boot and EFI are mounted on the same drive, please place each on it's own partition.")
    exit(1)
elif args.home is not None:
    if root_uuid == home_uuid:
        print("Error: Root and Home are mounted on the same drive, consider removing the -H/--home argument.")
        exit(1)
    elif boot_uuid == home_uuid:
        print("Error: Boot and Home are mounted on the same drive, consider removing the -H/--home argument.")
        exit(1)
    elif efi_uuid == home_uuid:
        print("Error: EFI and Home are mounted on the same drive, consider removing the -H/--home argument.")
        exit(1)
        
        
# With All Checks Clear and info gathered let's start installing

## extract the squashfs image to root from casper
squashfs_cmd = ['unsquashfs', '-f', '-d', listToString(args.root), image]
subprocess.run(squashfs_cmd)

## Enable bls_boot on EFI partiton
efi_flag_cmd = ['/usr/lib/pika/pikainstall/partition-helper.sh', 'flag', listToString(args.efi), 'bls_boot', 'on']
subprocess.run(efi_flag_cmd)


CHROOT_PATH = listToString(args.root)

# Write crypttab script if system has encryption
if root_encrypt != "luks_none":
    CRYPTTAB_ROOT_FILE_PATH = '/var/albius-crypttab-root.sh'
    CHROOT_CRYPTTAB_ROOT_FILE_PATH = os.path.join(CHROOT_PATH,CRYPTTAB_ROOT_FILE_PATH)
    print("writing to:")
    print(CHROOT_CRYPTTAB_ROOT_FILE_PATH)
    with open(CHROOT_CRYPTTAB_ROOT_FILE_PATH, "w") as file:
        albius_crypttab_root_file = _CRYPTTAB_ROOT_SETUP_FILE.format(
            ROOT_PART_UUID=root_uuid,
        )
        file.write(albius_crypttab_root_file)

# Write crypttab script if system has encryption
if args.home is not None:
    if home_encrypt != "luks_none":
        CRYPTTAB_FILE_PATH = '/var/albius-crypttab.sh'
        CHROOT_CRYPTTAB_FILE_PATH = os.path.join(CHROOT_PATH,CRYPTTAB_FILE_PATH)
        print("writing to:")
        print(CHROOT_CRYPTTAB_FILE_PATH)
        with open(CHROOT_CRYPTTAB_FILE_PATH, "w") as file:
            albius_crypttab_file = _CRYPTTAB_SETUP_FILE.format(
                HOME_PART_UUID=home_uuid,
                LUKS_PASSWD=home_passwd,
            )
            file.write(albius_crypttab_file)

# Write refind script if system has encryption
REFIND_FILE_PATH = '/var/albius-refind_linux.sh'
CHROOT_REFIND_FILE_PATH = os.path.join(CHROOT_PATH,REFIND_FILE_PATH)
print("writing to:")
print(CHROOT_REFIND_FILE_PATH)
with open(CHROOT_REFIND_FILE_PATH, "w") as file:
    refind_crypttab_file = _REFIND_SETUP_FILE.format(
        ROOT_PART_UUID=root_uuid,
    )
    file.write(refind_crypttab_file)
    

## Run pika-install-script
bind_dev_cmd = ['/usr/lib/pika/pikainstall/pika-install-host.sh', listToString(args.root)]
subprocess.run(bind_dev_cmd)

print("System installed!")
exit(0)
